# Generated by Django 3.0.6 on 2020-05-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notepad_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notepad_web_app.Document'),
        ),
    ]
