# Generated by Django 2.2.12 on 2020-05-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad_web_app', '0002_auto_20200530_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
