# Generated by Django 2.2.12 on 2020-05-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notepad_web_app', '0003_auto_20200531_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notepad_web_app.User'),
            preserve_default=False,
        ),
    ]
